### PR TITLE
[FEATURE] Enhanced Firework Video Quality & New Video Player Experience 🎆📹

### PR DESCRIPTION
**Pull request by aliciusschroeder**
While I thoroughly enjoy the bright and explosive display of our firework products, I couldn't help but feel a teeny tiny pang of sadness every time a YouTube video played in potato-quality. Don't we all love to see those sparkles in HD? 😉 Well, good news!

**What has changed?** 🎉

1. **Goodbye, low-res YouTube Iframes!** With the addition of our shiny new local server, we can now fetch those invaluable details of any YouTube video, including the hotlink URLs of the actual video files.

2. **Hello, `ytVideos.js`!** Crafted this utility file that simplifies our life by converting a YouTube video ID straight into the hotlink URL of its highest resolution version. This is not magic; it's just JavaScript (or maybe a bit of both).

3. **Welcome on board, `video.js` player!** Swapped the old YT iframe for this nifty player. It doesn't just look better; it also feeds our hungry eyes with the crispiest, highest resolution videos. Talk about an upgrade!

**Why is this change awesome?** 🌟

- **Usability Boost:** No more manual quality switching when reviewing 200+ fireworks. Time saved is time earned (or more time to enjoy fireworks)!

- **Future-ready:** This new setup gives us so much more control over the video playback experience. Thinking autoplay? Dreaming of automatic full screen? Custom interface? The sky's the limit (like our fireworks)!

**Next Steps:** 🛠

Would love to get some feedback and test this out in our staging environment. And, if everyone's happy, light the fuse and let this update skyrocket to production!

Cheers to clearer skies and crisper videos! 🎇

---

Please review the changes and let me know your thoughts! Also, if someone can test it out on different browsers, that would be amazing!

### CODE REVIEW

**Comment by aliciusschroeder** [comment]
Thanks for bringing the missing MIME type to my attention. It has been retrieved with the URL and correctly established.

Although I swiftly added the type support, I subsequently discovered another problem: It appears that Youtube is encoding all videos with high resolution from 720p and above (which we are using) without sound.

This problem is resolved now as well, as with my latest commits we're fetching the highest quality audio stream too and playing it in sync with our video.

I'd love to hear your feedback!

**Comment by CR1337** [comment]
Well, this seems to be tricky. There is the next set of errors:

```
Invalid URI. Load of media resource  failed. a4541d89-abc6-41d9-bfc6-0b65d985239c
Network Error ytVideos.js:52:21
    getYtVideo ytVideos.js:52
    (Async: promise callback)
    getYtVideo ytVideos.js:51
    getProduct Product.vue:318
    (Async: promise callback)
    getProduct Product.vue:312
    initialize Product.vue:296
    created Product.vue:416
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    callHook runtime-core.esm-bundler.js:3509
    applyOptions runtime-core.esm-bundler.js:3427
    finishComponentSetup runtime-core.esm-bundler.js:7341
    setupStatefulComponent runtime-core.esm-bundler.js:7265
    setupComponent runtime-core.esm-bundler.js:7197
    mountComponent runtime-core.esm-bundler.js:5599
    processComponent runtime-core.esm-bundler.js:5565
    patch runtime-core.esm-bundler.js:5040
    componentUpdateFn runtime-core.esm-bundler.js:5773
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    callWithErrorHandling runtime-core.esm-bundler.js:158
    flushJobs runtime-core.esm-bundler.js:357
    (Async: promise callback)
    queueFlush runtime-core.esm-bundler.js:270
    queuePostFlushCb runtime-core.esm-bundler.js:290
    queueEffectWithSuspense runtime-core.esm-bundler.js:1603
    scheduler runtime-core.esm-bundler.js:1773
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:363
    triggerRefValue reactivity.esm-bundler.js:974
    effect reactivity.esm-bundler.js:1135
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:974
    effect reactivity.esm-bundler.js:1135
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:974
    set value reactivity.esm-bundler.js:1018
    finalizeNavigation vue-router.mjs:3355
    pushWithRedirect vue-router.mjs:3220
    (Async: promise callback)
    pushWithRedirect vue-router.mjs:3187
    push vue-router.mjs:3112
    install vue-router.mjs:3551
    use runtime-core.esm-bundler.js:3752
    <anonymous> main.js:11
[Vue warn]: Unhandled error during execution of render function 
  at <Product onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:41:12
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Product onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:41:12
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.min.js:12:1362
Uncaught (in promise) TypeError: $data.productVideoData is undefined
    _sfc_render Product.vue:70
    renderComponentRoot runtime-core.esm-bundler.js:816
    componentUpdateFn runtime-core.esm-bundler.js:5764
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    callWithErrorHandling runtime-core.esm-bundler.js:158
    flushJobs runtime-core.esm-bundler.js:357
    promise callback*queueFlush runtime-core.esm-bundler.js:270
    queueJob runtime-core.esm-bundler.js:264
    scheduler runtime-core.esm-bundler.js:1778
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:363
    trigger reactivity.esm-bundler.js:335
    set2 reactivity.esm-bundler.js:487
    set runtime-core.esm-bundler.js:2986
    getProduct Product.vue:319
    promise callback*getProduct/< Product.vue:318
    promise callback*getProduct Product.vue:312
    initialize Product.vue:296
    created Product.vue:416
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    callHook runtime-core.esm-bundler.js:3509
    applyOptions runtime-core.esm-bundler.js:3427
    finishComponentSetup runtime-core.esm-bundler.js:7341
    setupStatefulComponent runtime-core.esm-bundler.js:7265
    setupComponent runtime-core.esm-bundler.js:7197
    mountComponent runtime-core.esm-bundler.js:5599
    processComponent runtime-core.esm-bundler.js:5565
    patch runtime-core.esm-bundler.js:5040
    componentUpdateFn runtime-core.esm-bundler.js:5773
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    callWithErrorHandling runtime-core.esm-bundler.js:158
    flushJobs runtime-core.esm-bundler.js:357
    promise callback*queueFlush runtime-core.esm-bundler.js:270
    queuePostFlushCb runtime-core.esm-bundler.js:290
    queueEffectWithSuspense runtime-core.esm-bundler.js:1603
    scheduler runtime-core.esm-bundler.js:1773
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:363
    triggerRefValue reactivity.esm-bundler.js:974
    effect reactivity.esm-bundler.js:1135
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:974
    effect reactivity.esm-bundler.js:1135
    triggerEffect reactivity.esm-bundler.js:373
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:974
    set value reactivity.esm-bundler.js:1018
    finalizeNavigation vue-router.mjs:3355
    pushWithRedirect vue-router.mjs:3220
    promise callback*pushWithRedirect vue-router.mjs:3187
    push vue-router.mjs:3112
    install vue-router.mjs:3551
    use runtime-core.esm-bundler.js:3752
    <anonymous> main.js:11
Product.vue:70:25
```

It looks like this:

Screenshot from 2023-09-07 19-13-22

**Comment by aliciusschroeder** [comment]
I completely concur with your observations. Dissecting the intricacies of a frequently updated, high-complexity video platform like YouTube just for the sheer pleasure of a 4K firework visualization can be quite challenging.

Upon further inspection, I've found that our implementation remains stable as long as we receive a valid response from our YouTube-parsing server. However, if you ever encounter an `undefined` state for the `productVideoData` variable, I'd recommend manually inspecting the data retrieval process. For instance, you can try making a request to [http://localhost:5624/?id=gy1B3agGNxw](http://localhost:5624/?id=gy1B3agGNxw).

Interestingly, specific modifications on YouTube's end might sometimes yield a JSON response where `success` is `true`, but the `data` field remains empty. Given our `yt2html` server's significant reliance on the `ytdl-core` package, it would be prudent to stay updated with their repository, especially any recent changes or issues. You can check it out here: [fent/node-ytdl-core](https://github.com/fent/node-ytdl-core).

During my testing, **I was able to replicate the error you mentioned and found a resolution by executing:
`npm i ytdl-core@4.10.0`** 

Fortunately, the `ytdl-core` repository is actively well maintained, and the contributors address any modifications required due to YouTube's evolving landscape very promptly. If we ever decide to release this project to a broader, non-technical audience, it's crucial for us to host this application component remotely and ensure its consistent functionality. For now, though, a periodic review of `ytdl-core` should suffice, especially given the reward of seamless 4K video streaming.

I hope this adjustment now allows you to partake in the beautiful and mesmerizing high-resolution fireworks as well!

**Comment by CR1337** [comment]
I ran `npm i ytdl-core@4.10.0` as you recommended. Unfortunately there are still errors:

```
Uncaught (in promise) TypeError: The element or ID supplied is not valid. (videojs)
    T video.min.js:21
    mounted Product.vue:297
video.min.js:21:36286
Invalid URI. Load of media resource  failed. a4541d89-abc6-41d9-bfc6-0b65d985239c
Network Error ytVideos.js:52:21
    getYtVideo http://localhost:5173/src/utils/ytVideos.js:52
[Vue warn]: Unhandled error during execution of render function 
  at <Product onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:41:12
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Product onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:41:12
Uncaught (in promise) TypeError: $data.productVideoData is undefined
    _sfc_render Product.vue:80
    renderComponentRoot runtime-core.esm-bundler.js:816
    componentUpdateFn runtime-core.esm-bundler.js:5764
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    callWithErrorHandling runtime-core.esm-bundler.js:158
    flushJobs runtime-core.esm-bundler.js:357
Product.vue:80:25
```
The website looks like this now:

Screenshot from 2023-09-09 16-05-52

I made you a collaborator and pushed your fork onto [this branch](https://github.com/CR1337/firework-rating/tree/better-video-player) to make the process easier.

**Comment by CR1337** [comment]
What was the argument against just opening a youtube tab and let the browser plugin handle the quality?

**Comment by aliciusschroeder** [comment]
Thank you for the update and for making me a contributor.

Regarding the errors you're encountering, I suspect that the frontend error message "Uncaught (in promise) TypeError: $data.productVideoData is undefined" is indicative of a failure in the yt2html5server part rather than the frontend. To further diagnose this, could you please provide the response you get when you run the following command?
```
curl http://localhost:5624/?id=gy1B3agGNxw
```

Now, addressing the topic of why we should prefer an integrated HD-player over simply opening a YouTube tab in my opinion:

1. **User Experience**: One of the cornerstones of our platform is providing a seamless and immersive experience. By keeping users within our ecosystem, they remain engaged and focused on our content. Redirecting to an external site can disrupt this flow (in fact the whole YouTube interface is optimised in keeping users on their platform rather than where they came from). 

2. **Control & Customization**: An integrated player grants us absolute control over the video experience. It's not just about playback; it's about creating a tailored viewing environment that fits our brand and our users' expectations. For example, if we want to remove the need to click the full-screen button every time, we can't do that easily on YouTube, but with our own video player it's easy to do.

In essence, while opening a YouTube tab might seem like the easy path, an integrated player assures quality, control, and a consistent, user-centric experience. By taking this route we provide our users with nothing but the best and remain scalable for the future.

**Comment by CR1337** [comment]
The response of running the curl command (with adapted port) is this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <link href="https://vjs.zencdn.net/8.5.2/video-js.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fireworks Rating</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
    <script src="https://vjs.zencdn.net/8.5.2/video.min.js"></script>
  </body>
</html>
```

Regarding your explanation on why we need this feature I am not really sure what you are talking about 😂
We are the only users for an app we use once a year. I am sure we manage to not get distracted by youtube like we did last year, remember? 😉

Please don't get me wrong. I really appreciate your effort and if you choose to continue putting work into this I am happy to assist like I did before. Nevertheless, regarding the allocation of our time resources, I am for a more practical approach that gets things done, that is actually rating the fireworks 🙃

**Pull request closed without merging**
